name = "Minorities MC"
author = "melinaracc"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ed7cfa7b86e1f2d4ac09b32301ab4fc1ba425983a073160ba537caa9a34cbe5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.174"
