name = "Minorities MC"
author = "melinaracc"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae6001cd6ddd129383c24596e8421535a4a2f0eab0843545081e581368af03ab"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.174"
