name = "Minorities MC"
author = "melinaracc"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfe7b5d479731fcce5d183dc467add715e9f7a2839c069aa5e7540f0993ea529"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.174"
