name = "Minorities MC"
author = "melinaracc"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b38e4ac03de24e0aa1d85944d149e56f53bb91f1769ea1e90b12edc800b6a53"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.174"
