name = "Minorities MC"
author = "melinaracc"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05bc28e80e13458686a35ff374fbff0a3df7967bc277de6a9e00e01bee0a6112"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.174"
