name = "Minorities MC"
author = "melinaracc"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8afd9a1e4c5e8ccae7b74ced1d788d6d6626aedbd617f232e6cbdcaba93d66e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.174"
